language: elixir

elixir:
  - '1.7.3'

services:
  - docker

env:
  - APP_NAME=discordbot

jobs:
  include:
    - stage: test
      install:
        - mix local.rebar --force
        - mix local.hex --force
        - mix deps.get
      script:
        - mix format --check-formatted
        - mix test --no-start

    - stage: deploy
      install:
        - docker --version
        - pip install --user awscli
        - export PATH=$PATH:$HOME/.local/bin
        - eval $(aws ecr get-login --no-include-email --region us-east-2)
        - export AWS_ACCOUNT_ID="$(aws sts get-caller-identity --output text --query 'Account')"
      script:
        - docker build -t "${APP_NAME}" .
        - docker tag "${APP_NAME}":latest "${AWS_ACCOUNT_ID}".dkr.ecr.us-east-2.amazonaws.com/"${APP_NAME}":latest
        - docker push "${AWS_ACCOUNT_ID}".dkr.ecr.us-east-2.amazonaws.com/"${APP_NAME}":latest

