version: '3'

services:
  
  discordbot:
    build:
      context: .
      args:
        MIX_ENV: dev
        CLEAN: "false"
    restart: on-failure
    depends_on:
      - rabbitmq

  discordbot-transcoder:
    build: https://github.com/alexweav/discordbot-transcoder.git
    #build:
    #  context: ../discordbot-transcoder
    restart: on-failure
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
