version: "3"

services:
  discordbot:
    image: 902538745451.dkr.ecr.us-east-2.amazonaws.com/discordbot:latest
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/discordbot-app
        awslogs-region: us-east-2
        awslogs-stream-prefix: ecs

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: discordbot
      RABBITMQ_DEFAULT_PASS: discordbot
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/discordbot-rmq
        awslogs-region: us-east-2
        awslogs-stream-prefix: ecs
