version: "3"

services:
  discordbot:
    image: 902538745451.dkr.ecr.us-east-2.amazonaws.com/discordbot:latest
    hostname: discordbot
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/discordbot-app
        awslogs-region: us-east-2
        awslogs-stream-prefix: ecs
    depends_on:
      - zookeeper

  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/discordbot-kafka
        awslogs-region: us-east-2
        awslogs-stream-prefix: ecs

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    hostname: zookeeper
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/discordbot-zookeeper
        awslogs-region: us-east-2
        awslogs-stream-prefix: ecs
