name: DiscordBot CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
    - uses: actions/checkout@v1

    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Linter
      env:
        mix_env: test
      run: mix format --check-formatted

    - name: Static Analysis
      env:
        mix_env: test
      run: mix credo

    - name: Run Tests
      run: mix test --no-start

    - name: Calculate Test Coverage
      env:
        mix_env: test
      run: |
        mix coveralls.json --umbrella --no-start
        bash <(curl -s https://codecov.io/bash)
