name: DiscordBot-PR

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    name: PR Build
    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
    - uses: actions/checkout@v1

    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Lint
      env:
        MIX_ENV: test
      run: mix format --check-formatted

    - name: Build
      env:
        MIX_ENV: test
      run: mix compile

    - name: Static Analysis
      env:
        MIX_ENV: test
      run: mix credo

    - name: Run Tests
      env:
        MIX_ENV: test
      run: mix test --no-start

    - name: Calculate Test Coverage
      env:
        MIX_ENV: test
      run: mix coveralls.json --umbrella --no-start

    - name: Upload Coverage to Codecov.io
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
