name: DiscordBot-PR

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
    - uses: actions/checkout@v1

    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Lint
      env:
        mix_env: test
      run: mix format --check-formatted

    - name: Build
      env:
        mix_env: test
      run: mix compile

    - name: Static Analysis
      env:
        mix_env: test
      run: mix credo

    - name: Run Tests
      env:
        mix_env: test
      run: mix test --no-start

    - name: Calculate Test Coverage
      env:
        mix_env: test
      run: mix coveralls.json --umbrella --no-start

    - name: Upload Coverage to Codecov.io
      env:
        codecov_token: ${{ secrets.CODECOV_TOKEN }}
      run: bash -c "bash <(curl -s https://codecov.io/bash)"
